export const  ICONS = {
    // LOGO:require('../assets/Images/Login/logo.png'),
    LOGO:require('../assets/Images/logoPC.png'),
    UNCHECKED:require('../assets/Images/Login/unCheckBox.png'),
    SUCCESS:require('../assets/Images/Login/success.png'),
    LANDING:require('../assets/Images/Landing/Landing.png'),
    LOCATION:require('../assets/Images/Landing/location.png'),
    GIRL:require('../assets/Images/Landing/girl.png'),
    HALFIMG:require('../assets/Images/Landing/image.png'),
    ADDHIGH:require('../assets/Images/Landing/addHigh.png'),
    ADDGradHIGH:require('../assets/Images/highlightGradient.png'),
    BOOKMARK:require('../assets/Images/Landing/bookmark.png'),
    DELETICON:require('../assets/Images/deleteIIcon.png'),
    BACKICONN:require('../assets/Images/BackIcon.png'),
    ADDDICON:require('../assets/Images/AddIcon.png'),

    //BOTTOM TAB 
    Home:require('../assets/Images/BottomTab/Home.png'),
    Message:require('../assets/Images/BottomTab/Message.png'),
    Subscription:require('../assets/Images/BottomTab/Subscription.png'),
    Service:require('../assets/Images/BottomTab/Subscription.png'),
    Profile:require('../assets/Images/BottomTab/Profile.png'),
    Setting:require('../assets/Images/BottomTab/Setting.png'),
    PROFILE:require('../assets/Images/image.png'),
    SEND:require('../assets/Images/send.png'),
    ATTECHED:require('../assets/Images/Attached.png'),
    ABOUT1:require('../assets/Images/about1.png'),
    ABOUT2:require('../assets/Images/about2.png'),
    ABOUT3:require('../assets/Images/about3.png'),
    CHECKWHITE:require('../assets/Images/CheckWhite.png'),
    DOWNICON:require('../assets/Images/DOWN.png'),
    Notification:require('../assets/Images/Notification.png'),
    Active:require('../assets/Images/gradient.png'),
    DISABLE:require('../assets/Images/outlineGradient.png'),
}